# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uni_v3
rollback_on_reorg: true
unordered_multichain_mode: true

contracts:
  - name: UniswapV3Factory
    handler: src/EventHandlers.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: UniswapV3Pool
    handler: src/EventHandlers.ts
    events:
      - event: Initialize(uint160 sqrtPriceX96, int24 tick)
      - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from

networks:
  - id: 1 # Ethereum Mainnet
    start_block: 12369621
    contracts:
      - name: UniswapV3Factory
        address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
      - name: UniswapV3Pool
  - id: 137 # Polygon
    start_block: 22757547
    contracts:
      - name: UniswapV3Factory
        address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
      - name: UniswapV3Pool
  - id: 42161 # Arbitrum One
    start_block: 165
    contracts:
      - name: UniswapV3Factory
        address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
      - name: UniswapV3Pool
  - id: 10 # Optimism
    start_block: 0
    contracts:
      - name: UniswapV3Factory
        address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
      - name: UniswapV3Pool
  - id: 43114 # Avalanche
    start_block: 27832972
    contracts:
      - name: UniswapV3Factory
        address: 0x740b1c1de25031C31FF4fC9A62f554A55cdC1baD
      - name: UniswapV3Pool
  - id: 8453 # Base
    start_block: 1371680
    contracts:
      - name: UniswapV3Factory
        address: 0x33128a8fC17869897dcE68Ed026d694621f6FDfD
      - name: UniswapV3Pool
  - id: 56 # Bsc
    start_block: 26324014
    contracts:
      - name: UniswapV3Factory
        address: 0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7
      - name: UniswapV3Pool
